sonar.projectKey=maloymanna_azure-security-powershell
sonar.organization=maloymanna

sonar.sources=scripts
sonar.tests=tests

sonar.test.inclusions=tests/*.ps1

sonar.externalIssuesReportPaths=psscriptanalyzer-report.json
sonar.testExecutionReportPaths=test-results.xml
