name: PowerShell CI

on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0

    - name: Install modules
      shell: pwsh
      run: |
        Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
        Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser      

    - name: Run PSScriptAnalyzer
      shell: pwsh
      run: |
        $results = Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning
        # Convert PowerShell objects returned to JSON object
        $issues = foreach ($r in $results) {
            @{
                engineId = "PSScriptAnalyzer"
                ruleId   = $r.RuleName
                severity = "MAJOR"
                type     = "CODE_SMELL"
                primaryLocation = @{
                    message = $r.Message
                    filePath = $r.ScriptPath
                    textRange = @{
                        startLine = $r.Line
                        endLine   = $r.Line
                    }
                }
            }
        }
        $wrapped = @{
            issues = $issues
        }
        $wrapped | ConvertTo-Json -Depth 10 | Out-File psscriptanalyzer-report.json -Encoding utf8        

    - name: Run Pester tests
      shell: pwsh
      run: |
        Invoke-Pester ./tests
  
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v7 # See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.verbose=true
          -Dsonar.projectKey=maloymanna_azure-security-powershell
          -Dsonar.organization=maloymanna

    - name: Sonar Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@v1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
